//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace soaptest2.statusPing {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integration.sprint.com/canonical/v1/interfaces/QuerySystemStatusService.ws" +
        "dl", ConfigurationName="statusPing.QuerySystemStatusPortType")]
    public interface QuerySystemStatusPortType {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://integration.sprint.com/canonical/v1/interfaces/QuerySystemStatusService.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="urn:#ping", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        soaptest2.statusPing.pingResponse ping(soaptest2.statusPing.pingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:#ping", ReplyAction="*")]
        System.Threading.Tasks.Task<soaptest2.statusPing.pingResponse> pingAsync(soaptest2.statusPing.pingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ping", WrapperNamespace="http://integration.sprint.com/canonical/v1/interfaces/QuerySystemStatusService.ws" +
        "dl", IsWrapped=true)]
    public partial class pingRequest {
        
        public pingRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pingResponse", WrapperNamespace="http://integration.sprint.com/canonical/v1/interfaces/QuerySystemStatusService.ws" +
        "dl", IsWrapped=true)]
    public partial class pingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool status;
        
        public pingResponse() {
        }
        
        public pingResponse(bool status) {
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuerySystemStatusPortTypeChannel : soaptest2.statusPing.QuerySystemStatusPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuerySystemStatusPortTypeClient : System.ServiceModel.ClientBase<soaptest2.statusPing.QuerySystemStatusPortType>, soaptest2.statusPing.QuerySystemStatusPortType {
        
        public QuerySystemStatusPortTypeClient() {
        }
        
        public QuerySystemStatusPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuerySystemStatusPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuerySystemStatusPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuerySystemStatusPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soaptest2.statusPing.pingResponse soaptest2.statusPing.QuerySystemStatusPortType.ping(soaptest2.statusPing.pingRequest request) {
            return base.Channel.ping(request);
        }
        
        public bool ping() {
            soaptest2.statusPing.pingRequest inValue = new soaptest2.statusPing.pingRequest();
            soaptest2.statusPing.pingResponse retVal = ((soaptest2.statusPing.QuerySystemStatusPortType)(this)).ping(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soaptest2.statusPing.pingResponse> soaptest2.statusPing.QuerySystemStatusPortType.pingAsync(soaptest2.statusPing.pingRequest request) {
            return base.Channel.pingAsync(request);
        }
        
        public System.Threading.Tasks.Task<soaptest2.statusPing.pingResponse> pingAsync() {
            soaptest2.statusPing.pingRequest inValue = new soaptest2.statusPing.pingRequest();
            return ((soaptest2.statusPing.QuerySystemStatusPortType)(this)).pingAsync(inValue);
        }
    }
}
